from __future__ import annotations

SEED_RESOURCES = [
    {
        'slug': 'openai-whisper',
        'record_type': 'resource',
        'name': 'Whisper',
        'provider': 'OpenAI',
        'category': 'stt',
        'summary': 'Open-source multilingual speech-to-text model that is a common baseline for local or containerized transcription pipelines.',
        'resource_url': 'https://github.com/openai/whisper',
        'tags': ['open-source', 'asr', 'batch', 'local-model'],
        'local_model_ready': True,
        'hosted_service': False,
        'open_source': True,
        'deployment': 'local / container',
        'pricing_model': 'self-hosted',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://github.com/openai/whisper',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'assemblyai-universal',
        'record_type': 'resource',
        'name': 'Universal-Streaming',
        'provider': 'AssemblyAI',
        'category': 'stt',
        'summary': 'Hosted STT API with streaming transcription, diarization, and summarization features that are useful for production voice apps.',
        'resource_url': 'https://www.assemblyai.com/',
        'tags': ['hosted-api', 'streaming', 'transcription'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed API',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://www.assemblyai.com/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'deepgram-nova-3',
        'record_type': 'resource',
        'name': 'Nova-3',
        'provider': 'Deepgram',
        'category': 'stt',
        'summary': 'Speech recognition service optimized for low latency voice workloads, call analytics, and realtime transcription.',
        'resource_url': 'https://deepgram.com/',
        'tags': ['stt', 'realtime', 'call-center'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed API',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://deepgram.com/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'elevenlabs-tts',
        'record_type': 'resource',
        'name': 'ElevenLabs',
        'provider': 'ElevenLabs',
        'category': 'tts',
        'summary': 'Hosted TTS platform for expressive voices, multilingual speech synthesis, and conversational voice experiences.',
        'resource_url': 'https://elevenlabs.io/',
        'tags': ['tts', 'voice-cloning', 'managed-api'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed API',
        'pricing_model': 'subscription + usage',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://elevenlabs.io/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'cartesia-sonic',
        'record_type': 'resource',
        'name': 'Sonic',
        'provider': 'Cartesia',
        'category': 'tts',
        'summary': 'Low-latency speech synthesis stack aimed at realtime voice agents and natural backchanneling.',
        'resource_url': 'https://cartesia.ai/',
        'tags': ['tts', 'realtime', 'voice-agent'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed API',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://cartesia.ai/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'piper-tts',
        'record_type': 'resource',
        'name': 'Piper',
        'provider': 'Rhasspy',
        'category': 'tts',
        'summary': 'Fast open-source local text-to-speech runtime that works well for on-device and self-hosted voice applications.',
        'resource_url': 'https://github.com/rhasspy/piper',
        'tags': ['tts', 'open-source', 'local-model'],
        'local_model_ready': True,
        'hosted_service': False,
        'open_source': True,
        'deployment': 'local / container',
        'pricing_model': 'self-hosted',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://github.com/rhasspy/piper',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'ollama-local-llms',
        'record_type': 'resource',
        'name': 'Ollama',
        'provider': 'Ollama',
        'category': 'slm',
        'summary': 'Simple local model runtime for running and serving open models with an HTTP API suitable for local app backends.',
        'resource_url': 'https://ollama.com/',
        'tags': ['local-model', 'llm-runtime', 'open-source'],
        'local_model_ready': True,
        'hosted_service': False,
        'open_source': True,
        'deployment': 'local / container',
        'pricing_model': 'self-hosted',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://ollama.com/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'llama-cpp',
        'record_type': 'resource',
        'name': 'llama.cpp',
        'provider': 'ggerganov',
        'category': 'slm',
        'summary': 'Lightweight local inference stack that is useful for embedding or low-latency small model deployment in voice systems.',
        'resource_url': 'https://github.com/ggerganov/llama.cpp',
        'tags': ['local-model', 'inference', 'open-source'],
        'local_model_ready': True,
        'hosted_service': False,
        'open_source': True,
        'deployment': 'local / container',
        'pricing_model': 'self-hosted',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://github.com/ggerganov/llama.cpp',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'openai-realtime-api',
        'record_type': 'resource',
        'name': 'Realtime API',
        'provider': 'OpenAI',
        'category': 's2s',
        'summary': 'Speech-to-speech and multimodal realtime endpoint for conversational agents, tool use, and low-latency turn taking.',
        'resource_url': 'https://platform.openai.com/docs/guides/realtime',
        'tags': ['s2s', 'realtime', 'voice-agent'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed API',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://platform.openai.com/docs/guides/realtime',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'livekit-agents',
        'record_type': 'resource',
        'name': 'LiveKit Agents',
        'provider': 'LiveKit',
        'category': 'voice-agent',
        'summary': 'Agent framework and realtime media stack for building production voice assistants on WebRTC and SIP transport.',
        'resource_url': 'https://docs.livekit.io/agents/',
        'tags': ['voice-agent', 'realtime', 'webrtc', 'telephony'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': True,
        'deployment': 'self-hosted or managed cloud',
        'pricing_model': 'open-source + managed cloud',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://docs.livekit.io/agents/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'pipecat-framework',
        'record_type': 'resource',
        'name': 'Pipecat',
        'provider': 'Pipecat',
        'category': 'orchestration',
        'summary': 'Open-source Python framework for chaining STT, TTS, LLM, transport, and business logic into realtime voice pipelines.',
        'resource_url': 'https://github.com/pipecat-ai/pipecat',
        'tags': ['voice-agent', 'pipeline', 'open-source', 'python'],
        'local_model_ready': True,
        'hosted_service': False,
        'open_source': True,
        'deployment': 'local / container / cloud',
        'pricing_model': 'self-hosted',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://github.com/pipecat-ai/pipecat',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'daily-webrtc',
        'record_type': 'resource',
        'name': 'Daily',
        'provider': 'Daily',
        'category': 'realtime',
        'summary': 'Realtime audio and video infrastructure used by multimodal assistants, contact-center copilots, and live meeting agents.',
        'resource_url': 'https://www.daily.co/',
        'tags': ['realtime', 'webrtc', 'media-infra'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed API',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://www.daily.co/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'twilio-voice',
        'record_type': 'resource',
        'name': 'Twilio Voice',
        'provider': 'Twilio',
        'category': 'telephony',
        'summary': 'Programmable telephony APIs for SIP, PSTN, and contact-center integrations that can connect cloud or local voice agents.',
        'resource_url': 'https://www.twilio.com/voice',
        'tags': ['telephony', 'sip', 'pstn'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed cloud',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://www.twilio.com/voice',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'nomic-embed-text',
        'record_type': 'resource',
        'name': 'nomic-embed-text',
        'provider': 'Nomic',
        'category': 'embedding',
        'summary': 'Embedding model that works well for compact local semantic search pipelines and retrieval-augmented generation.',
        'resource_url': 'https://ollama.com/library/nomic-embed-text',
        'tags': ['embedding', 'local-model', 'semantic-search'],
        'local_model_ready': True,
        'hosted_service': False,
        'open_source': True,
        'deployment': 'local / container',
        'pricing_model': 'self-hosted',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://ollama.com/library/nomic-embed-text',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'bge-m3',
        'record_type': 'resource',
        'name': 'BGE-M3',
        'provider': 'BAAI',
        'category': 'embedding',
        'summary': 'Multilingual embedding model family that is useful when the application needs semantic search over mixed technical documentation.',
        'resource_url': 'https://huggingface.co/BAAI/bge-m3',
        'tags': ['embedding', 'multilingual', 'semantic-search'],
        'local_model_ready': True,
        'hosted_service': False,
        'open_source': True,
        'deployment': 'local / container',
        'pricing_model': 'self-hosted',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://huggingface.co/BAAI/bge-m3',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'vapi',
        'record_type': 'resource',
        'name': 'Vapi',
        'provider': 'Vapi',
        'category': 'voice-agent',
        'summary': 'Managed platform for building voice agents with tool calling, telephony integrations, and analytics.',
        'resource_url': 'https://vapi.ai/',
        'tags': ['voice-agent', 'telephony', 'managed'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed cloud',
        'pricing_model': 'subscription + usage',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://vapi.ai/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'retell-ai',
        'record_type': 'resource',
        'name': 'Retell AI',
        'provider': 'Retell AI',
        'category': 'voice-agent',
        'summary': 'Voice agent platform for phone and realtime assistants with telephony infrastructure and agent management features.',
        'resource_url': 'https://www.retellai.com/',
        'tags': ['voice-agent', 'telephony', 'managed'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed cloud',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://www.retellai.com/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'modal-serverless',
        'record_type': 'resource',
        'name': 'Modal',
        'provider': 'Modal',
        'category': 'hosting',
        'summary': 'GPU-capable serverless platform that is useful for hosting voice inference workers, batch jobs, and speech pipelines.',
        'resource_url': 'https://modal.com/',
        'tags': ['hosting', 'gpu', 'serverless'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed cloud',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://modal.com/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'runpod',
        'record_type': 'resource',
        'name': 'RunPod',
        'provider': 'RunPod',
        'category': 'hosting',
        'summary': 'GPU infrastructure service that can host speech models, embeddings, and voice-agent orchestration backends.',
        'resource_url': 'https://www.runpod.io/',
        'tags': ['hosting', 'gpu', 'inference'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed cloud',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://www.runpod.io/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'railway',
        'record_type': 'resource',
        'name': 'Railway',
        'provider': 'Railway',
        'category': 'container',
        'summary': 'Developer-friendly container hosting platform suited for shipping small FastAPI or Node services behind a voice app.',
        'resource_url': 'https://railway.app/',
        'tags': ['container', 'hosting', 'developer-experience'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed cloud',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://railway.app/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'fly-io',
        'record_type': 'resource',
        'name': 'Fly.io',
        'provider': 'Fly.io',
        'category': 'container',
        'summary': 'Global container platform that can run low-latency edge services for voice gateways or agent backends.',
        'resource_url': 'https://fly.io/',
        'tags': ['container', 'edge', 'hosting'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed cloud',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://fly.io/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'aws-ecs-fargate',
        'record_type': 'resource',
        'name': 'ECS Fargate',
        'provider': 'AWS',
        'category': 'hosting',
        'summary': 'Container orchestration option for enterprises that want managed infrastructure for API layers and voice microservices.',
        'resource_url': 'https://aws.amazon.com/fargate/',
        'tags': ['hosting', 'container', 'enterprise'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': False,
        'deployment': 'managed cloud',
        'pricing_model': 'usage-based',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://aws.amazon.com/fargate/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
    {
        'slug': 'langfuse-observability',
        'record_type': 'resource',
        'name': 'Langfuse',
        'provider': 'Langfuse',
        'category': 'observability',
        'summary': 'Observability stack for LLM and agent traces that is useful when debugging voice workflows, prompts, and latency.',
        'resource_url': 'https://langfuse.com/',
        'tags': ['observability', 'tracing', 'agents'],
        'local_model_ready': False,
        'hosted_service': True,
        'open_source': True,
        'deployment': 'self-hosted or managed cloud',
        'pricing_model': 'open-source + managed cloud',
        'source_name': 'Seed catalog',
        'source_type': 'seed',
        'source_url': 'https://langfuse.com/',
        'last_updated': '2026-03-10T00:00:00+00:00',
    },
]

DEFAULT_FEED_SOURCES = [
    {
        'name': 'LiveKit releases',
        'url': 'https://github.com/livekit/livekit/releases.atom',
        'kind': 'atom',
        'category_hint': 'realtime',
        'enabled': True,
        'update_interval_hours': 24,
    },
    {
        'name': 'Pipecat releases',
        'url': 'https://github.com/pipecat-ai/pipecat/releases.atom',
        'kind': 'atom',
        'category_hint': 'orchestration',
        'enabled': True,
        'update_interval_hours': 24,
    },
    {
        'name': 'Ollama releases',
        'url': 'https://github.com/ollama/ollama/releases.atom',
        'kind': 'atom',
        'category_hint': 'slm',
        'enabled': True,
        'update_interval_hours': 24,
    },
    {
        'name': 'Piper releases',
        'url': 'https://github.com/rhasspy/piper/releases.atom',
        'kind': 'atom',
        'category_hint': 'tts',
        'enabled': True,
        'update_interval_hours': 24,
    },
]

SAMPLE_FEED_ITEMS = [
    {
        'title': 'LiveKit Agents adds better SIP and telephony workflows',
        'link': 'https://docs.livekit.io/agents/',
        'published': '2026-03-11T10:15:00+00:00',
        'summary': 'A release focused on improving call bridging, media routing, and voice agent session handling for production deployments.',
        'source_name': 'LiveKit releases',
        'category_hint': 'voice-agent',
        'provider': 'LiveKit',
    },
    {
        'title': 'Pipecat improves structured tool events and realtime turns',
        'link': 'https://github.com/pipecat-ai/pipecat',
        'published': '2026-03-11T12:00:00+00:00',
        'summary': 'The latest Pipecat release sharpens orchestration hooks for tool calling, streaming turns, and multimodal session control.',
        'source_name': 'Pipecat releases',
        'category_hint': 'orchestration',
        'provider': 'Pipecat',
    },
    {
        'title': 'Ollama publishes a fresh local runtime build for agent backends',
        'link': 'https://ollama.com/',
        'published': '2026-03-11T13:30:00+00:00',
        'summary': 'The runtime update focuses on stability and model serving ergonomics that help local AI application stacks stay reliable.',
        'source_name': 'Ollama releases',
        'category_hint': 'slm',
        'provider': 'Ollama',
    },
]
